### PR TITLE
Fix bad Euchre discards/passes

### LINKED ISSUE #233: Euchre: Bad bot pass when calling NT Alone?
> Just finished a game with three bot players, and my bot partner twice took No Trump alone, then passed me an ace, while keeping a lower card in that same suit. We got set both times, and I think if they had kept the ace we would not have got set. Seems there is an error in the programming if they are doing that.

% PBN ---------------------------
[Event "Trickster Cards: Play Euchre - Play to 10, stick-the-dealer, go under, call for best, with no trump"]
[UTCDate "2024.01.03"]
[UTCTime "05:07:09"]
[LocalDateTime "1/2/2024 9:07 PM PST"
[GameCode "Euchre"]
[GameOptionsJson "{"stickTheDealer":true,"allowNotrump":true,"callForBest":true,"goUnder":true,"noWatching":true}"]
[GameScores "S:6 11 6 11"]
[West "Bessie (Auto)"]
[North "Mitch (Auto)"]
[East "Jo (Auto)"]
[South "Erin (4302670)"]
[Dealer "S"]
[Deal "S:J9.9.Q.J KQ..K.T9 .A.J9.AK AT.KQ..Q"]
[Undealt "HTDADTHJ"]
[Declarer "N"]
[Contract "NT alone"]
[Auction "W"]
Pass Pass Pass Pass
Pass NTalone - -
[CardsPassed "S:N:DQ"]
[CardsPassed "N:S:HA"]
[Play "W"]
C9 CA CQ -
CT CK ST -
DK DQ HQ -
SQ D9 SA -
SK DJ HK -

### PR DESCRIPTION
**Pull request by antross**
Fix #233

The discard algorithm (also used for passing a card away from the maker in call-for-best) is pretty simple and could sometimes lead to passing good off-suit cards, especially in no trump.

Fixed by adding a couple of extra early sort conditions to prefer keeping off-suit Aces and protected Kings if possible.

### CODE REVIEW

File: TricksterBots/Bots/Euchre/EuchreBot.cs [hunk 1]
```diff
@@ -184,12 +184,19 @@ public override List<Card> SuggestDiscard(SuggestDiscardState<EuchreOptions> sta
...
-                        { suit = s, count = hand.Count(c => EffectiveSuit(c) == s), lowRank = hand.Where(c => EffectiveSuit(c) == s).Min(RankSort) })
-                    .OrderBy(sc => sc.count)
+                    {
+                        suit = s,
+                        count = hand.Count(c => EffectiveSuit(c) == s),
+                        lowRank = hand.Where(c => EffectiveSuit(c) == s).Min(RankSort),
+                        highRank = hand.Where(c => EffectiveSuit(c) == s).Max(RankSort)
+                    })
+                    .OrderBy(sc => sc.lowRank == (int)Rank.Ace) //  don't get rid of off-suit Aces unless we have to
+                    .ThenBy(sc => sc.count == 2 && sc.highRank == (int)Rank.King) //  don't get rid of protection for an off-suit King unless we have to
```
Comment (antross) [inline TricksterBots/Bots/Euchre/EuchreBot.cs:198]: Use `RankSort` here too. Just use `RankSort(new Card(sc.suit, Rank.Ace))` etc.
